import {escape as e,money,stamp} from './format.js';
import {button} from './views.js';
export class AdminUI {
 constructor(context){Object.assign(this,context);this.selected=new Set();this.names=new Map();this.data=null;this.search='';this.offset=0;this.sort='name';this.player=null;document.addEventListener('change',event=>{if(event.target.dataset.target){if(event.target.checked){this.selected.add(event.target.dataset.target);this.names.set(event.target.dataset.target,event.target.parentElement.textContent.trim());}else this.selected.delete(event.target.dataset.target);const el=document.querySelector('#selected-count');if(el)el.textContent=this.selected.size+'명 선택';}});}
 async load(){if(!this.api.adminToken){this.modal('관리자 강화 인증','<form id="admin-unlock-form"><p class="muted">일반 PIN과 별도로 설정한 관리자 암호를 입력하세요. 운영 권한은 15분간 유지됩니다.</p><label>강화 암호<input name="secret" type="password" autocomplete="off" required></label><button type="submit" class="primary wide">관리자 인증</button></form>');return;}const r=await this.read('adminOverview',{search:this.search,sort:this.sort,offset:this.offset});this.data=r;this.render();}
 render(){const main=document.querySelector('#main');if(!this.data){main.innerHTML='<h2>관리자 모드</h2><p class="muted">관리자 인증 후 운영 현황을 불러옵니다.</p>'+button('인증하기','admin');return;}const d=this.data;main.innerHTML=`<div class="page-head"><div><span class="eyebrow">OPERATOR CONSOLE</span><h2>운영 현황</h2></div>${button('새로고침','adminRefresh')}</div><p class="footnote">시세 기준 ${stamp(d.marketTime)} · 최근 5분 요청 기준 활성 ${d.active}명</p><div class="metric-grid"><div class="metric"><span class="muted">전체 플레이어</span><strong>${d.count}명</strong></div><div class="metric"><span class="muted">누적 체결</span><strong>${d.receiptCount}건</strong></div></div>${d.health?`<p class="footnote">시장 트리거 ${e(d.health.lastTick)} · ${d.health.tickMs}ms<br>최근 저장 오류 ${e(d.health.lastStorageError||'기록 없음')}</p>`:''}<section class="section"><div class="admin-grid">${[['adminNotice','공지 작성'],['adminReward','보상 등록'],['adminRestriction','이용 제한'],['adminMaintenance','점검 설정'],['adminMarket','시장 운영'],['adminNews','뉴스 작성'],['adminEconomy','경제 지표'],['adminSupport','고객센터 대화'],['adminReports','제보·제안'],['adminAudits','운영 기록']].map(([id,n])=>button(n,id)).join('')}</div></section><form id="admin-search-form" class="row"><input name="search" placeholder="한글 아이디 검색" value="${e(this.search)}" aria-label="플레이어 검색"><button type="submit">검색</button></form><form id="admin-sort-form"><label>플레이어 정렬<select name="sort">${[['name','이름'],['cash','현금'],['total','총자산'],['lastSeen','최근 활동'],['joined','가입일'],['lifetimeSeconds','플레이 시간']].map(([k,n])=>`<option value="${k}" ${this.sort===k?'selected':''}>${n}</option>`).join('')}</select></label><button type="submit" class="wide">정렬 적용</button></form><div class="row spread" style="margin:16px 0"><strong id="selected-count">${this.selected.size}명 선택</strong>${button('선택 전체 해제','adminClear','','link-button')}</div><div class="list">${d.players.map(p=>`<div class="list-row"><label class="check"><input type="checkbox" data-target="${p.id}" ${this.selected.has(p.id)?'checked':''}>${e(p.name)}</label><div><small>${money(p.total)}</small><br>${button('상세','adminPlayer',`data-id="${p.id}"`,'link-button')}</div></div>`).join('')}</div><div class="row">${this.offset?button('이전','adminPrev','','grow'):''}${d.next!==null?button('다음','adminNext','','grow'):''}</div><p class="footnote">선택 대상은 검색·페이지 변경 후에도 유지됩니다. 게시·지급 전에 대상 목록을 확인합니다.</p>`;}
 targetsText(){return [...this.selected].map(id=>this.names.get(id)||this.data?.players.find(p=>p.id===id)?.name||id).join(', ');}
 async action(action,target){
  if(action==='admin'){await this.navigate('admin');return;}
  if(action==='adminRefresh')return this.load();if(action==='adminNext'){this.offset=this.data.next;return this.load();}if(action==='adminPrev'){this.offset=Math.max(0,this.offset-30);return this.load();}if(action==='adminClear'){this.selected.clear();return this.render();}
  if(action==='adminReturn'){this.api.proxyToken='';this.apply(null);await this.call('adminReturn');await this.navigate('admin');if(this.player)await this.action('adminPlayer',{dataset:{id:this.player.account.id}});return;}
  if(action==='adminPlayer'){const r=await this.read('adminPlayer',{targetId:target.dataset.id});this.player=r.player;const a=r.player.account;this.modal(a.name+' 기본 정보',`<div class="receipt"><div><span>가입</span><strong>${stamp(a.joined)}</strong></div><div><span>총자산</span><strong>${money(r.player.total)}</strong></div><div><span>현금</span><strong>${money(a.cash)}</strong></div><div><span>회차 DAY</span><strong>${r.player.day}</strong></div><div><span>누적 로그인</span><strong>${a.logins}회</strong></div></div>${button('플레이어 시점','adminProxy',`data-id="${a.id}"`,'primary wide')}${button('자산·해금·업적 정정','adminAdjust',`data-id="${a.id}"`,'wide')}<p class="footnote">대리 화면에서 실제 매수·매도·예약·수령·설정을 수정합니다. 로그인·플레이 통계는 늘리지 않습니다.</p>`);return;}
  if(action==='adminProxy'){const r=await this.call('adminProxy',{targetId:target.dataset.id});this.api.proxyToken=r.proxyToken;const state=await this.read('sync');this.apply(state.snapshot);return this.navigate('home');}
  if(action==='adminReports'){this.modal('제보·제안',this.data.reports.map(r=>`<article class="news-card"><span class="tag">${e(r.status)}</span><h3>${e(r.type)}</h3><p>${e(r.body)}</p><p class="muted">작성 계정 ${e(r.accountId)}<br>답변 이메일 ${e(r.email||'미입력')}<br>${stamp(r.at)}</p><p class="footnote">${e(r.environment)}</p>${button('채택 및 보상 연결','adminAdopt',`data-id="${r.id}" data-player="${r.accountId}"`,'wide')}${r.status==='채택'&&!r.rewardBatch?'<p class="error">채택 후 보상 미지급</p>':''}</article>`).join('')||'<p class="empty">제보가 없습니다.</p>');return;}
  if(action==='adminAdopt'){await this.call('adminReport',{reportId:target.dataset.id,status:'채택',reason:'제안 채택'});this.selected=new Set([target.dataset.player]);this.reportId=target.dataset.id;return this.action('adminReward',target);}
  if(action==='adminAudits'){this.modal('관리자 전용 운영 기록',this.data.audits.map(r=>`<div class="news-card"><h3>${e(r.action)}</h3><p class="muted">${e(r.actor)} · ${stamp(r.at)}<br>대상 ${e(JSON.stringify(r.target))}</p><p>${e(r.reason)}</p><details><summary>변경 전후</summary><pre style="white-space:pre-wrap;font-size:11px">${e(JSON.stringify({before:r.before,after:r.after},null,2))}</pre></details></div>`).join('')||'<p>운영 기록이 없습니다.</p>');return;}
  if(action==='adminNotice'){this.modal('전체·선택 공지',`<form id="admin-notice-form"><label>발송 범위<select name="scope"><option value="selected">선택 대상 ${this.selected.size}명</option><option value="all">전체 플레이어</option></select></label><p class="footnote">선택: ${e(this.targetsText())||'없음'}</p><label>기존 공지 수정<select name="noticeId"><option value="">새 공지</option>${this.data.notices.map(n=>`<option value="${n.id}">${e(n.title)}</option>`).join('')}</select></label><label>제목<input name="title" maxlength="100" required></label><label>내용<textarea name="body" maxlength="4000" required></textarea></label><label>상태<select name="status"><option>초안</option><option>게시</option><option>내림</option></select></label><button class="primary wide">대상과 내용 확인</button></form>`);return;}
  if(action==='adminReward'){this.modal('보상 등록',`<form id="admin-reward-form"><p>선택 대상 ${this.selected.size}명</p><p class="footnote">${e(this.targetsText())||'먼저 플레이어를 선택하세요.'}</p><label>보상 종류<select name="kind"><option value="cash">게임머니</option><option value="security">주식·ETF</option><option value="badge">배지·칭호</option></select></label><label>게임머니 금액<input name="amount" type="number" min="1" value="10000"></label><label>종목${this.stockSelect()}</label><label>주식·ETF 수량<input name="quantity" type="number" min="1" value="1"></label><label>배지·칭호 이름<input name="badge" maxlength="50"></label><label>사유<textarea name="reason" required maxlength="500"></textarea></label><p class="footnote">즉시 자산에 더하지 않고 수령 가능한 보상으로 전달합니다.</p><button class="primary wide">지급 내용 확인</button></form>`);return;}
  if(action==='adminRestriction'){this.modal('이용 제한·해제',`<form id="admin-restriction-form"><p>선택 대상 ${this.selected.size}명 · ${e(this.targetsText())}</p><label>조치<select name="enabled"><option value="true">이용 제한</option><option value="false">제한 해제</option></select></label><label>제한 일수 (0 = 해제 전까지)<input name="days" type="number" min="0" max="3650" value="0"></label><label>사유<textarea name="reason" maxlength="500" required></textarea></label><button class="primary wide">내용 확인</button></form>`);return;}
  if(action==='adminMaintenance'){this.modal('점검 모드',`<form id="admin-maintenance-form"><label>운영 상태<select name="enabled"><option value="true">점검 시작</option><option value="false">점검 해제</option></select></label><label>점검 사유<textarea name="reason" maxlength="500" required>${e(this.data.maintenance.reason)}</textarea></label><label>예상 종료 또는 소요 시간<input name="until" maxlength="100" value="${e(this.data.maintenance.until)}" placeholder="예: 한국 시간 22시까지"></label><p class="footnote">일반 접속·신규 조작을 막습니다. 시장과 예약 처리는 계속됩니다. 예상 종료가 지나도 자동 해제되지 않습니다.</p><button class="primary wide">내용 확인</button></form>`);return;}
  if(action==='adminAdjust'){const a=this.player.account;this.modal('플레이어 상태 정정',`<form id="admin-adjust-form" data-id="${a.id}"><p>${e(a.name)} · 진행 중 예약은 취소하고 정정합니다.</p><label>정정 후 현금<input name="cash" type="number" min="0" value="${a.cash}" required></label><label>회차 DAY<input name="day" type="number" min="1" max="10000" value="${this.player.day}" required></label><label>보유 정정 종목 (선택)${this.stockSelect(true)}</label><label>정정 후 수량<input name="quantity" type="number" min="0" value="0"></label><label>정정 후 매입 원가<input name="cost" type="number" min="0" value="0"></label><label>추가할 배지 (선택)<input name="badge" maxlength="50"></label><label>내부 정정 사유<textarea name="reason" maxlength="500" required></textarea></label><button class="primary wide">변경 내용 확인</button></form>`);return;}
  if(action==='adminMarket'){this.modal('시장 운영',`<form id="admin-market-form"><label>종목${this.stockSelect()}</label><label>조치<select name="operation"><option value="price">가격 정정 (일일 범위 이내)</option><option value="halt">거래정지</option><option value="resume">거래 재개</option><option value="delist">상장폐지 예고</option><option value="split">주식 분할</option><option value="financial">실적 정정</option><option value="dividend">배당 정책 정정</option><option value="listing">새 종목 상장</option></select></label><label>변경 가격<input name="price" type="number" min="1" value="70000"></label><label>폐지까지 일수 (최소 3일)<input name="days" type="number" min="3" max="365" value="3"></label><label>폐지 주당 회수금 (공란 = 비상장 보유)<input name="settlement" type="number" min="0"></label><label>분할 비율<input name="ratio" type="number" min="2" max="100" value="2"></label><details><summary>기업 실적·배당 입력</summary><label>매출<input name="revenue" type="number" min="0" value="300000000000"></label><label>영업이익<input name="profit" type="number" value="20000000000"></label><label>부채<input name="debt" type="number" min="0" value="100000000000"></label><label>주당 배당 정책<input name="perShare" type="number" min="0" value="0"></label></details><details><summary>신규 상장 정보</summary><label>새 종목코드<input name="listingSymbol" pattern="[0-9]{6}" maxlength="6"></label><label>기업명<input name="name" maxlength="40"></label><label>시장<select name="market"><option>KOSPI</option><option>KOSDAQ</option></select></label><label>산업<select name="sector"><option>반도체</option><option>자동차</option><option>에너지</option><option>바이오</option><option>디지털</option><option>소비재</option></select></label></details><label>운영 사유<textarea name="reason" required maxlength="500"></textarea></label><button class="primary wide">변경 내용 확인</button></form>`);return;}
  if(action==='adminNews'){this.modal('뉴스 작성',`<form id="admin-news-form"><label>수정 대상<select name="newsId"><option value="">새 뉴스</option>${this.getSnapshot().news.map(n=>`<option value="${n.id}">${e(n.title)}</option>`).join('')}</select></label><label>관련 종목${this.stockSelect(true)}</label><label>제목<input name="title" maxlength="100" required></label><label>핵심 사실<textarea name="body" maxlength="4000" required></textarea></label><label>운영 사유<input name="reason" maxlength="500" required></label><button class="primary wide">내용 확인</button></form>`);return;}
  if(action==='adminEconomy'){this.modal('경제 지표 정정',`<form id="admin-economy-form"><label>금리 (%)<input name="rate" type="number" step="0.01" min="0" max="30" value="3" required></label><label>물가 (%)<input name="inflation" type="number" step="0.01" min="-10" max="100" value="2.3" required></label><label>경기 지수<input name="activity" type="number" min="0" max="200" value="100" required></label><label>사유<input name="reason" required maxlength="500"></label><button class="primary wide">내용 확인</button></form>`);return;}
 }
 review(action,d){
  const name=id=>this.names.get(id)||this.data?.players.find(p=>p.id===id)?.name||id;
  const stock=id=>this.getSnapshot().stocks.find(x=>x.id===id)?.name||id;
  const rows=[];if(d.targets)rows.push('대상: '+(d.targets==='all'?'전체 플레이어':d.targets.map(name).join(', ')||'선택 없음'));if(d.targetId)rows.push('플레이어: '+name(d.targetId));if(d.symbol)rows.push('종목: '+stock(d.symbol));
  if(d.reward)rows.push('보상: '+(d.reward.kind==='cash'?money(d.reward.amount):d.reward.kind==='security'?stock(d.reward.symbol)+' '+d.reward.quantity+'주':d.reward.badge));
  const labels={title:'제목',body:'내용',status:'상태',reason:'사유',cash:'정정 후 현금',day:'회차 DAY',quantity:'수량',cost:'매입 원가',badge:'추가 배지',price:'변경 가격',days:'폐지까지 일수',ratio:'분할 비율',settlement:'주당 회수금',until:'종료 시점',rate:'금리 (0.01% 단위)',inflation:'물가 (0.01% 단위)',activity:'경기 지수',revenue:'매출',profit:'영업이익',debt:'부채',perShare:'주당 배당',listingSymbol:'새 종목코드',name:'기업명',market:'시장',sector:'산업'};
  if('enabled'in d)rows.push('조치: '+(d.enabled?'시작 / 적용':'해제'));
  if(d.operation)rows.push('시장 조치: '+({price:'가격 정정',halt:'거래정지',resume:'거래 재개',delist:'상장폐지 예고',split:'주식 분할',financial:'실적 정정',dividend:'배당 정책 정정',listing:'새 종목 상장'}[d.operation]||d.operation));
  for(const [k,label]of Object.entries(labels))if(d[k]!==undefined&&d[k]!==''&&!(d.operation&&['price','days','ratio','settlement'].includes(k)&&!({price:['price'],delist:['days','settlement'],split:['ratio']}[d.operation]||[]).includes(k)))rows.push(label+': '+(d[k]===null?'별도 확정 전':d[k]));
  return rows.join('\n');
 }
 stockSelect(optional=false){return `<select name="symbol">${optional?'<option value="">변경 없음 / 전체</option>':''}${this.getSnapshot().stocks.map(x=>`<option value="${x.id}">${e(x.name)}</option>`).join('')}</select>`;}
 async submit(form,fd){const d=Object.fromEntries(fd),t=this.getSnapshot()?.serverTime||Date.now();
  if(form.id==='admin-unlock-form'){const r=await this.call('adminUnlock',{secret:d.secret});this.api.adminToken=r.adminToken;this.close();return this.load();}
  if(form.id==='admin-search-form'){this.search=d.search;this.offset=0;return this.load();}if(form.id==='admin-sort-form'){this.sort=d.sort;this.offset=0;return this.load();}
  if(form.id==='admin-confirm-form'){await this.call(this.confirmation.action,this.confirmation.data);this.close();this.toast('운영 작업을 저장했습니다.');this.reportId=null;return this.load();}
  let action,data;
  if(form.id==='admin-notice-form'){action='adminNotice';data={...d,targets:d.scope==='all'?'all':[...this.selected]};if(!data.noticeId)delete data.noticeId;}
  if(form.id==='admin-reward-form'){action='adminReward';data={targets:[...this.selected],reward:{kind:d.kind,amount:Number(d.amount),quantity:Number(d.quantity),symbol:d.symbol,badge:d.badge},reason:d.reason,reportId:this.reportId};}
  if(form.id==='admin-restriction-form'){action='adminRestriction';data={targets:[...this.selected],enabled:d.enabled==='true',until:Number(d.days)?t+Number(d.days)*86400000:null,reason:d.reason};}
  if(form.id==='admin-maintenance-form'){action='adminMaintenance';data={...d,enabled:d.enabled==='true'};}
  if(form.id==='admin-adjust-form'){action='adminAdjust';data={...d,targetId:form.dataset.id,cash:Number(d.cash),day:Number(d.day),quantity:Number(d.quantity),cost:Number(d.cost)};}
  if(form.id==='admin-market-form'){action='adminMarket';data={...d,revenue:Number(d.revenue),profit:Number(d.profit),debt:Number(d.debt),perShare:Number(d.perShare),price:Number(d.price),at:t+Number(d.days)*86400000,ratio:Number(d.ratio),settlement:d.settlement===''?null:Number(d.settlement)};}
  if(form.id==='admin-news-form'){action='adminNews';data=d;}
  if(form.id==='admin-economy-form'){action='adminEconomy';data={rate:Math.round(Number(d.rate)*100),inflation:Math.round(Number(d.inflation)*100),activity:Number(d.activity),reason:d.reason};}
  if(!action)return;this.confirmation={action,data};this.modal('운영 작업 최종 확인',`<p>아래 내용으로 실제 게임 데이터를 변경합니다.</p><pre class="card" style="white-space:pre-wrap;font-size:12px">${e(this.review(action,data))}</pre><form id="admin-confirm-form"><button class="primary wide">확정하여 적용</button></form>`);
 }
}
