import {escape as e,money,percent,candleData,chart,change,icon} from './format.js';
export function miniCandles(points){
 const bars=candleData(points).slice(-24);if(!bars.length)return '<span class="mini-empty">기록 대기</span>';
 const low=Math.min(...bars.map(b=>b.low)),high=Math.max(...bars.map(b=>b.high)),span=high-low||1,y=v=>5+(high-v)/span*42,step=144/Math.max(bars.length,8);
 return `<svg class="mini-candles" viewBox="0 0 154 54" role="img" aria-label="최근 5분봉: 최저 ${money(low)}, 최고 ${money(high)}">${bars.map((b,i)=>{const x=5+i*step,c=b.close>b.open?'#e44640':b.close<b.open?'#367ee7':'#738396';return `<line x1="${x}" x2="${x}" y1="${y(b.high)}" y2="${y(b.low)}" stroke="${c}"/><rect x="${x-2}" y="${Math.min(y(b.open),y(b.close))}" width="4" height="${Math.max(1,Math.abs(y(b.open)-y(b.close)))}" fill="${c}"/>`;}).join('')}</svg>`;
}
export function compositionParts(s){return [['현금',s.account.cash,'#2889dd'],['주식',s.stockValue,'#f45657'],['ETF',s.etfValue,'#934ee4'],['미수령 배당',s.dividends,'#eeb322']].map(([label,value,color])=>({label,value,color,share:s.total?value/s.total*100:0}));}
export function composition(s){
 const parts=compositionParts(s);let offset=0;const stops=parts.map(p=>{const start=offset;offset+=p.share;return `${p.color} ${start}% ${offset}%`;}).join(',');
 return `<section class="card"><h3>자산 구성</h3><div class="asset-composition"><div class="asset-donut" role="img" aria-label="${parts.map(p=>p.label+' '+p.share.toFixed(1)+'%').join(',')}" style="background:${s.total?'conic-gradient('+stops+')':'#e4dfc6'}"><div><small>총자산</small><strong>${money(s.total)}</strong></div></div><div class="composition-legend">${parts.map(p=>`<div><i style="background:${p.color}"></i><span>${p.label}<strong>${money(p.value)}</strong></span><small>${p.share.toFixed(1)}%</small></div>`).join('')}</div></div><p class="footnote">예약된 현금·주식도 각 항목에 한 번 포함됩니다.</p></section>`;
}
export function portfolioPanel(s,period='all',home=false){
 const days={day:1,week:7,month:30,all:Infinity}[period]??Infinity,points=s.assetHistory.filter(p=>p.at>=s.serverTime-days*86400000).map(p=>[p.at,p.total]),base=s.account.contributedCash??s.account.startingCash??0,profit=s.total-base;
 return `<section class="portfolio-panel"><div class="portfolio-summary"><h3>${home?'나의 수익률':'총 자산'}</h3><strong class="portfolio-total ${home?(profit>=0?'up':'down'):''}">${home?percent(base?profit/base*100:0):money(s.total)}</strong><p class="portfolio-profit ${profit>=0?'up':'down'}">${profit>=0?'▲':'▼'} ${money(Math.abs(profit))}${home?'':`<br>${percent(base?profit/base*100:0)}`}</p><div class="portfolio-message">${home?'뉴스를 읽고<br>나만의 투자를 시작해요!':'내 투자 현황을<br>한눈에 확인하세요.'}</div></div><div class="portfolio-graph"><div class="tabs">${[['day','1일'],['week','1주'],['month','1개월'],['all','전체']].map(([id,label])=>`<button data-action="period" data-period="${id}" aria-pressed="${id===period}" class="${id===period?'selected':''}">${label}</button>`).join('')}</div>${chart(points,'총자산 기록')}</div><small class="portfolio-note">지원 자금 대비 · 실제 자산 기록</small></section>`;
}
export function shortcuts(s){const tiles=[['market','거래소','주식 사고팔기','market'],['assets','내 자산','보유 주식 현황','assets'],['news','뉴스','실시간 주요 소식','news'],[s.attendance?.visible?'attendance':'friends',s.attendance?.visible?'출석 보상':'친구',s.attendance?.visible?'오늘 보상 받기':'함께 투자하기','gift'],['achievements','업적','나의 도전 기록','trophy'],['rewards','보상함','배당과 보상 받기','chest']];return `<nav class="shortcut-grid" aria-label="홈 바로가기">${tiles.filter(t=>!s.proxy||t[0]!=='friends').map(([action,title,sub,art],i)=>`<button data-action="${action}" class="shortcut tile-${i}" style="--tile-art:url('./assets/ui/reference/tile-${art}.webp')"><span class="tile-copy"><strong>${title}</strong><small>${sub}</small></span><span class="tile-arrow" aria-hidden="true">›</span></button>`).join('')}</nav>`;}
export function marketPulse(s){if(!s.stocks)return '';const stocks=s.stocks.filter(x=>x.market!=='ETF'&&x.status==='상장'),up=stocks.filter(x=>change(x)>0).length,down=stocks.filter(x=>change(x)<0).length;return `<section class="market-pulse"><h3>오늘의 시장 현황</h3><div class="row spread"><span class="up">상승 <strong>${up}</strong></span><span class="down">하락 <strong>${down}</strong></span><span>보합 <strong>${stocks.length-up-down}</strong></span></div><p class="footnote">현재 상장 주식 ${stocks.length}종 · 전일 종가 대비</p></section>`;}
export function orderSubset(orders,tab){return orders.filter(o=>tab==='전체'||(tab==='예약매수'?o.kind==='limitBuy':tab==='예약매도'?o.kind==='limitSell':['stop','oco'].includes(o.kind)));}
