import {miniCandles,composition,portfolioPanel,shortcuts,marketPulse,orderSubset} from './game-panels.js';
import {companyDescriptions,companyLogoUrl} from './companies.js';
import {growthCard} from './progression-ui.js';
import {newsTitle,newsParagraphs,newsImageUrl,newsCategories,newsCategory} from './news-content.js';
import {escape as e,money,compact,stamp,percent,change,chart,candles} from './format.js';
export const button=(text,action,extra='',cls='')=>`<button type="button" data-action="${action}" ${extra} class="${cls}">${text}</button>`;
export const amount=v=>`<button class="money-button" data-action="amount" data-value="${v}" title="${money(v)}">${compact(v)}</button>`;
const row=(label,value)=>`<div><span class="muted">${label}</span><strong>${value}</strong></div>`;
const heading=(title,sub,action='')=>`<div class="page-head"><div><h2>${title}</h2><p class="muted">${sub}</p></div>${action}</div>`;
const kinds={assets:'총자산',realized:'누적 실현손익',shares:'동시 보유 주수',companies:'동시 보유 종목',news:'뉴스 읽기',time:'실제 플레이 시간',holding:'연속 보유 일수',dates:'플레이 날짜',industries:'산업 탐색',explore:'기업 탐색',memos:'투자 메모',reward:'특별 배지'};
export const achievementName=(a)=>a.title||`${kinds[a.kind]||a.kind} ${a.kind==='time'?(a.goal<3600?a.goal/60+'분':a.goal/3600+'시간'):a.goal?.toLocaleString('ko-KR')}`;
export function loginView(mode='login',status=''){
 return `<section class="auth"><img class="auth-art" src="./assets/ui/header.webp" alt="" width="720" height="210"><h1>주식왕 시뮬레이션</h1><div class="tabs"><button data-action="loginTab" data-mode="login" class="${mode==='login'?'selected':''}">로그인</button><button data-action="loginTab" data-mode="signup" class="${mode==='signup'?'selected':''}">회원가입</button></div><p id="auth-status" class="error" ${status?'':'hidden'}>${e(status)}</p><form id="auth-form" data-mode="${mode}"><label for="name">아이디</label><input id="name" name="name" autocomplete="username" maxlength="12" required placeholder="한글 2~12자"><label for="pin">비밀번호</label><input id="pin" name="pin" type="password" inputmode="numeric" autocomplete="${mode==='signup'?'new-password':'current-password'}" pattern="[0-9]{4}" maxlength="4" minlength="4" required placeholder="비밀번호 입력" title="숫자 4자리"><label class="check"><input name="remember" type="checkbox" checked>로그인 유지</label>${mode==='signup'?'<label for="pin-confirm">비밀번호 확인</label><input id="pin-confirm" name="pinConfirm" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required autocomplete="new-password"><label class="check"><input id="consent" name="consent" type="checkbox" required>가상 투자 안내 확인</label>':'<details><summary class="muted">운영자 로그인</summary><label for="admin-secret">관리자 강화 암호</label><input id="admin-secret" name="adminSecret" type="password" autocomplete="off"></details>'}<button class="primary wide" type="submit">${mode==='signup'?'회원가입':'로그인'}</button></form></section>`;
}
export function home(s,period='all'){
 const leaders=s.stocks.filter(x=>x.status==='상장'&&x.market!=='ETF').sort((a,b)=>change(b)-change(a)).slice(0,3);
 return `${heading('홈',`${e(s.account.name)}님`,button('알림함','inbox'))}${portfolioPanel(s,period)}${shortcuts(s)}<section class="card"><div class="section-title"><h3>오늘의 주요 종목</h3>${button('전체 보기','market','','link-button')}</div><div class="leader-grid">${leaders.map(x=>`<button data-action="detail" data-symbol="${x.id}">${companyLogo(x)}<strong>${e(x.name)}</strong>${miniCandles(x.history)}<b>${money(x.price)}</b><small class="${change(x)>=0?'up':'down'}">${percent(change(x))}</small></button>`).join('')}</div><p class="footnote">현재 상장 주식 중 전일 대비 상승률순</p></section>${growthCard(s.account.growth)}<div class="list">${s.proxy?'':button('친구','friends')}${button('경제 지표','economy')}${button('내 총자산 자세히 보기','total')}</div>`;
}
export function market(s,filter){
 const locked=filter.market==='ETF'&&s.day<4;let stocks=s.stocks.filter(x=>filter.market==='폐지'?x.status==='비상장':x.market===filter.market&&x.status!=='비상장').filter(x=>(x.name.toLowerCase().includes(filter.search.toLowerCase())||x.id.includes(filter.search))&&(!filter.favorites||s.account.settings.favorites.includes(x.id)));
 if(filter.sort==='name')stocks.sort((a,b)=>a.name.localeCompare(b.name,'ko'));if(filter.sort==='up')stocks.sort((a,b)=>change(b)-change(a));if(filter.sort==='down')stocks.sort((a,b)=>change(a)-change(b));if(filter.sort==='held')stocks.sort((a,b)=>(s.holdings[b.id]?.quantity||0)-(s.holdings[a.id]?.quantity||0));
 const top=[...stocks].sort((a,b)=>change(b)-change(a))[0];
 return `${heading('거래소','모든 플레이어가 같은 시장을 공유합니다',button('예약 주문','orders'))}<div class="tabs">${[['KOSPI','코스피'],['KOSDAQ','코스닥'],['ETF','ETF'],['폐지','상장폐지']].map(([id,n])=>`<button class="${filter.market===id?'selected':''}" data-action="marketTab" data-market="${id}">${n}</button>`).join('')}</div><label class="sr-label" for="search">기업 검색</label><input id="search" type="search" placeholder="기업 이름 또는 종목코드를 검색하세요" value="${e(filter.search)}"><div class="row spread"><label class="check"><input id="favorites" type="checkbox" ${filter.favorites?'checked':''}>관심종목만</label><select id="sort" aria-label="정렬" style="width:120px;margin-top:12px">${[['name','이름순'],['up','상승률순'],['down','하락률순'],['held','보유순']].map(([id,n])=>`<option value="${id}" ${filter.sort===id?'selected':''}>${n}</option>`).join('')}</select></div><p class="footnote">전일 대비는 전날 마지막 가격 기준입니다.</p><div id="market-results">${locked?lockedView(s,4,'ETF','구성자산에 나누어 투자하는 펀드입니다.'):stocks.map(x=>stockCard(s,x,top?.id)).join('')||'<div class="empty">조건에 맞는 종목이 없습니다.</div>'}</div>`;
}
export function companyLogo(x){const url=companyLogoUrl(x);return '<span class="company-logo" aria-hidden="true"><span>'+e(x.name.slice(0,2))+'</span>'+(url?'<img src="'+url+'" alt="" loading="lazy" referrerpolicy="no-referrer">':'')+'</span>';}
export function stockCard(s,x,top){const h=s.holdings[x.id],c=change(x);return `<article class="stock" data-symbol="${x.id}"><div class="stock-main">${companyLogo(x)}<div><h3>${e(x.name)}</h3><span class="muted">${e(x.sector)}</span> ${x.id===top?'<span class="tag gold">상승률 1위</span>':''}</div><div class="stock-price"><strong data-price="${x.id}" data-amount="${x.price}">${money(x.price)}</strong><p class="${c>=0?'up':'down'}">${percent(c)}</p></div></div><div class="stock-chart">${miniCandles(x.history)}</div><div class="stock-actions">${button(s.account.settings.favorites.includes(x.id)?'★':'☆','favorite',`data-symbol="${x.id}" aria-label="${e(x.name)} 관심종목"`,'favorite')}<span class="muted">${h?h.quantity.toLocaleString()+'주 보유':'미보유'}</span>${button('상세','detail',`data-symbol="${x.id}"`)}${x.status==='상장'?button('매수','buy',`data-symbol="${x.id}"`,'secondary')+button('예약','reserve',`data-symbol="${x.id}"`):`<span class="tag">${e(x.status)}</span>`}</div></article>`;}
export function lockedView(s,day,name,description){const date=new Date(s.account.started+32400000+(day-1)*86400000).toISOString().slice(0,10);return `<div class="card"><span class="tag">DAY ${day} 해금</span><h3 style="margin:14px 0">${name}</h3><p class="muted">${description}</p><p class="footnote">${date} 00:00부터 이용할 수 있습니다. 현재 DAY ${s.day}입니다.</p></div>`;}
export function detail(s,x,chartPeriod='day'){const interval={day:300000,month:3600000,all:86400000}[chartPeriod]||300000;const h=s.holdings[x.id],c=change(x);return `${button('돌아가기','market','','back')}<div class="page-head"><div><span class="eyebrow">${e(x.market)} / ${x.id}</span><h2 class="company-heading">${companyLogo(x)}${e(x.name)}</h2></div>${button(s.account.settings.favorites.includes(x.id)?'★':'☆','favorite',`data-symbol="${x.id}" aria-label="관심종목"`)}</div><div class="balance" data-price="${x.id}" data-amount="${x.price}">${money(x.price)}</div><p class="${c>=0?'up':'down'}">${percent(c)} <span class="muted">전일 대비</span> ${x.price>=x.high?'<span class="tag gold">신고가</span>':''}</p><nav class="tabs" aria-label="차트 기간">${[['day','5분봉'],['month','1시간봉'],['all','일봉']].map(([id,label])=>button(label,'chartPeriod',`data-period="${id}" aria-pressed="${id===chartPeriod}"`,id===chartPeriod?'selected':'')).join('')}</nav>${candles(x.history,[...(s.trades||[]).filter(v=>v.symbol===x.id).map(v=>({...v,kind:v.side,label:(v.side==='buy'?'매수':'매도')+' '+v.quantity+'주'})),...s.news.filter(n=>n.symbol===x.id).map(n=>({...n,kind:'news',label:n.title}))],interval,chartPeriod==='day'?undefined:x.chartBars?.[chartPeriod==='month'?'hour':'day'])}${button('목표가 알림 설정','priceAlert',`data-symbol="${x.id}"`,'wide')}<div class="row" style="margin:20px 0">${button('매수','buy',`data-symbol="${x.id}"`,'grow buy-button')}${button('매도','sell',`data-symbol="${x.id}"`,'grow sell-button')}${button('예약','reserve',`data-symbol="${x.id}"`,'grow')}</div><div class="card"><h3>어떤 기업인가요?</h3><p class="muted" style="margin-top:10px">${e(companyDescriptions[x.id]||x.description)}</p><p class="footnote">실제 기업 이름을 사용하지만 가격과 실적, 사건은 가상입니다.</p><div class="receipt">${row('관련 산업',e(x.sector))}${row('상장일',e(x.listed))}${row('최고가',money(x.high))}${row('최저가',money(x.low))}${row('보유 / 매도 가능',`${h?.quantity||0} / ${h?.available||0}주`)}</div></div>${x.market==='ETF'?x.fund?`<div class="card"><h3>ETF 운용 장부</h3><div class="receipt">${row('추정 순자산가치 iNAV',money(x.iNAV))}${row('확정 NAV',money(x.nav))}${row('거래가 괴리율',percent((x.price/x.iNAV-1)*100))}${row('발행 좌수',x.fund.units.toLocaleString())}${row('펀드 현금',money(x.fund.cash))}${row('배당 미수금',money(x.fund.receivable))}${row('부채',money(x.fund.liability))}</div><p class="footnote">연 보수 0.2% · 일요일 자정 재조정 · 일요일 21시 분배 수령 가능</p>${Object.entries(x.fund.positions).map(([id,q])=>`<p class="muted">${e(s.stocks.find(v=>v.id===id)?.name||id)} · ${q.toLocaleString()}주</p>`).join('')}</div>`:lockedView(s,4,'ETF 운용 장부','DAY 4에 구성자산과 거래가 열립니다.'):s.day<2?button('기업 실적표','financials','','wide'):`<div class="card"><h3>기업 실적</h3>${(x.financials||[]).slice().reverse().map(f=>`<p class="footnote">${stamp(f.at)} · 분기</p><div class="receipt">${row('매출',compact(f.revenue))}${row('영업이익',compact(f.profit))}${row('부채',compact(f.debt))}</div>`).join('')}</div>`}<section class="section"><h3>관련 뉴스</h3>${news(s,s.news.filter(n=>n.symbol===x.id).slice(0,5),false)}</section>`;}
const newsPicture=(n,thumbnail=false)=>`<img class="news-picture" src="${newsImageUrl(n,thumbnail)}" width="960" height="640" alt="" loading="lazy" decoding="async" onerror="this.remove()">`;
export function news(s,list=s.news,header=true,category='전체'){
 if(!newsCategories.includes(category))category='전체';
 const groups=list.filter(n=>category==='전체'||newsCategory(n)===category).sort((a,b)=>b.at-a.at).reduce((groups,n)=>{const date=stamp(n.at).slice(0,10);(groups[date]||=[]).push(n);return groups;},{});
 const tabs=header?`<nav class="news-categories" aria-label="뉴스 분류">${newsCategories.map(name=>button(name,'newsCategory',`data-category="${name}" aria-pressed="${name===category}"`,name===category?'active':'')).join('')}</nav>`:'';
 return `${header?heading('뉴스','게임 속 가상 시장 소식')+marketPulse(s):''}${tabs}${Object.entries(groups).map(([date,items])=>`<section class="news-date"><h3>${date}</h3>${items.map(n=>`<button class="news-preview" data-action="newsArticle" data-id="${e(n.id)}">${newsPicture(n,true)}<span class="row spread"><span class="tag">${e(newsCategory(n))} · ${e(n.sector)}</span><time>${stamp(n.at).slice(11)}</time></span><strong>${e(newsTitle(n))}</strong></button>`).join('')}</section>`).join('')||`<p class="empty">${category==='전체'?'새 소식을 준비하고 있어요.':'이 분류에 등록된 뉴스가 없습니다.'}</p>`}`;
}
export function newsArticle(s,n){return `${button('돌아가기','newsBack','','back')}<article class="news-article"><div class="row spread"><span class="tag">${e(n.sector)}</span><time>${stamp(n.at)}</time></div><h2>${e(newsTitle(n))}</h2><p class="article-label">시뮬레이션 뉴스 · 이미지는 주제별 공통 삽화입니다.</p>${newsPicture(n)}${newsParagraphs(n).map(line=>`<p>${e(line)}</p>`).join('')}${s.day<5&&n.beginner?`<aside class="card"><h3>처음 읽는 뉴스라면</h3><p>${e(n.beginner)}</p></aside>`:''}${n.symbol?`${miniCandles(s.stocks?.find(x=>x.id===n.symbol)?.history||[])}${button('관련 기업 보기','detail',`data-symbol="${e(n.symbol)}"`,'wide')}`:''}</article>`;}
export function assets(s,period='all'){let sector={};Object.entries(s.holdings).forEach(([id,h])=>{const x=s.stocks.find(v=>v.id===id);sector[x.sector]=(sector[x.sector]||0)+h.value;});return `${heading('내 자산','보유한 기업과 나의 투자 성과',button('예약 주문','orders'))}${portfolioPanel(s,period)}${composition(s)}${growthCard(s.account.growth)}<div class="card"><p class="muted">주식·ETF 평가액</p><div class="balance">${amount(s.stockValue+s.etfValue)}</div><div class="receipt">${row('평가손익',money(Object.values(s.holdings).reduce((v,h)=>v+h.profit,0)))}${row('누적 실현손익',money(s.account.realized))}${row('매수 가능 현금',money(s.availableCash))}</div>${button('내 총자산 보기','total','','wide secondary')}</div>${Object.entries(s.holdings).map(([id,h])=>{const x=s.stocks.find(v=>v.id===id);return `<div class="card"><div class="row spread"><h3>${e(x.name)}</h3><span class="tag">${e(x.status)}</span></div><div class="receipt">${row('보유 / 매도 가능',`${h.quantity} / ${h.available}주`)}${row('평균 매수가 · 비용 포함',money(h.average))}${row('현재가',money(h.price))}${row('매입금액',money(h.cost))}${row('평가금액',money(h.value))}${row('평가손익',`<span class="${h.profit>=0?'up':'down'}">${money(h.profit)} / ${h.cost?percent(h.profit/h.cost*100):'무상 취득'}</span>`)}</div><div class="row">${button('상세','detail',`data-symbol="${id}"`,'grow')}${button('매도','sell',`data-symbol="${id}"`,'grow')}${button('예약','reserve',`data-symbol="${id}"`,'grow')}</div>${x.status==='비상장'?'<p class="footnote">유효한 거래가 없어 0원으로 보수 평가합니다. 회수금 확정을 의미하지 않습니다.</p>':''}</div>`;}).join('')||'<p class="empty">아직 보유한 종목이 없습니다.<br>거래소에서 첫 기업을 만나 보세요.</p>'}<section class="section"><h3>산업별 투자 비중</h3>${Object.entries(sector).map(([name,v])=>`<p class="muted" style="margin-top:14px">${e(name)} · ${percent(v/(s.stockValue+s.etfValue||1)*100)}</p><div class="bar"><span style="width:${v/(s.stockValue+s.etfValue||1)*100}%"></span></div>`).join('')}<p class="footnote">주식·ETF 평가액 기준. ETF는 상품 분류로 표시합니다.</p></section>`;}
export function total(s){const items=[['현금',s.account.cash],...Object.entries(s.holdings).map(([id,h])=>[`${s.stocks.find(x=>x.id===id)?.name} ${money(h.price)} × ${h.quantity}주`,h.value]),['받을 배당·분배금',s.dividends]];return `${button('돌아가기','home','','back')}${heading('내 총자산','같은 시점의 가격으로 정확하게.')}<div class="card"><p id="sum-status" class="muted">자산 합산 완료 · ${items.length}/${items.length}</p><div id="total-number" class="balance" data-final="${s.total}">${compact(s.total)}</div><p class="footnote">${stamp(s.marketTime)} 시세 기준</p><div class="composition">${[s.account.cash,s.stockValue,s.etfValue,s.dividends].map(v=>`<span style="width:${s.total?v/s.total*100:0}%"></span>`).join('')}</div><div class="asset-legend">${[['현금',s.account.cash],['주식',s.stockValue],['ETF',s.etfValue],['미수령 금액',s.dividends]].map(([name,value],i)=>`<div><i class="asset-color color-${i}"></i><span>${name}</span><strong>${money(value)}</strong></div>`).join('')}</div></div><div class="card receipt">${items.map(([name,v])=>`<div class="sum-item" data-amount="${v}"><span class="muted">${e(name)}</span><strong>${amount(v)}</strong></div>`).join('')}<div class="total"><span>총자산</span><strong>${money(s.total)}</strong></div></div><p class="footnote">예약에 묶인 현금과 주식은 한 번 포함합니다. 매도 시 비용은 차감하지 않은 평가액입니다. 배당 수령은 받을 금액을 현금으로 옮기므로 총자산이 다시 늘지 않습니다.</p>${button('최신 상태 확인','sync','','wide')}`;}
export function orders(s,tab='전체'){const orders=orderSubset(s.orders,tab),active=s.orders.filter(o=>o.status==='대기');return `${button('돌아가기','market','','back')}${heading('예약 주문','미접속 중에도 공통 시장에서 처리합니다.')}<nav class="tabs order-tabs" aria-label="예약 분류">${['전체','예약매수','예약매도','자동매도'].map(t=>button(t,'orderTab',`data-tab="${t}" aria-pressed="${tab===t}"`,tab===t?'selected':'')).join('')}</nav><div class="metric-grid"><div class="metric"><span>대기 주문</span><strong>${active.length}건</strong></div><div class="metric"><span>매수 예약금 · 수수료 포함</span><strong>${money(active.reduce((v,o)=>v+(o.reserved||0),0))}</strong></div></div><p class="footnote">지정가는 불리한 가격에 체결하지 않습니다. 손절은 조건 충족 후 첫 유효 가격으로 체결되어 조건가와 다를 수 있습니다.</p>${orders.map(o=>{const x=s.stocks.find(x=>x.id===o.symbol);return `<div class="card" data-order="${o.id}"><div class="row spread"><h3>${e(x?.name||o.symbol)}</h3><span class="tag ${o.status==='체결'?'gold':''}">${e(o.status)}</span></div><p>${({limitBuy:'지정가 매수',limitSell:'지정가 매도',stop:'손절 조건부 매도',oco:'익절·손절 묶음'})[o.kind]} · ${o.quantity}주</p><div class="receipt">${row('조건가',money(o.price))}${o.stop?row('손절 조건가',money(o.stop)):''}${row('주문시각',stamp(o.at))}${row('만료',o.expires?stamp(o.expires):'직접 취소 전까지')}</div>${x?miniCandles(x.history):''}${o.reason?`<p class="error">${e(o.reason)}</p>`:''}${o.otherLeg?`<p class="muted">${o.filledLeg} 체결 · 반대 조건 취소</p>`:''}${o.status==='대기'?button('예약 취소','cancel',`data-id="${o.id}"`,'wide'):o.receiptId?button('체결 영수증','receipt',`data-id="${o.receiptId}"`,'wide'):''}</div>`;}).join('')||'<div class="empty">등록한 예약 주문이 없습니다.</div>'}`;}
export function rewards(s,tab='보상'){
 const list=s.claims.filter(c=>tab==='배당금'?!c.reward:!!c.reward),ready=list.filter(c=>c.payAt<=s.serverTime),cash=ready.filter(c=>!c.reward||c.reward.kind==='cash').reduce((v,c)=>v+c.net,0);
 return `${button('돌아가기','home','','back')}${heading('보상함','받을 금액과 도착한 소식',button('알림함','inbox'))}<nav class="tabs" aria-label="보상 분류">${['보상','배당금','우편함'].map(t=>button(t,'rewardTab',`data-tab="${t}" aria-pressed="${tab===t}"`,tab===t?'selected':'')).join('')}</nav>${tab==='우편함'?s.announcements.map(n=>`<article class="card"><h3>${e(n.title)}</h3><p>${e(n.body)}</p><small>${stamp(n.at)}</small></article>`).join('')||'<p class="empty">도착한 우편이 없습니다.</p>':`<section class="portfolio-panel"><h3>지금 받을 수 있는 현금</h3><strong class="portfolio-total">${money(cash)}</strong><p>${ready.length}건 · 주식·배지는 현금 합계에서 제외</p>${button('모든 보상·배당 수령','claim','data-id="all"','wide primary')}</section>${list.map(c=>`<article class="card"><span class="tag gold">${c.reward?'관리자 보상':'배당·분배금'}</span><h3>${e(c.name||c.reason||'보상')}</h3><p class="balance">${c.reward?.kind==='security'?`${e(s.stocks.find(x=>x.id===c.reward.symbol)?.name)} ${c.reward.quantity}주`:c.reward?.kind==='badge'?e(c.reward.badge):money(c.net)}</p><p class="footnote">${c.reward?'':`세전 ${money(c.gross)} · 세금 ${money(c.tax)} · `}${stamp(c.payAt)}부터 수령 가능</p>${button(c.payAt<=s.serverTime?'받기':'지급 대기','claim',`data-id="${c.id}" ${c.payAt>s.serverTime?'disabled':''}`,'wide primary')}</article>`).join('')||'<p class="empty">수령할 항목이 없습니다.</p>'}`}`;
}
export function inbox(s,tab='전체'){
 const read=new Set(s.readAlerts||[]),items=(s.alerts||[]).map(n=>({...n,category:n.category||'시세'})).sort((a,b)=>b.at-a.at),filtered=items.filter(n=>tab==='전체'||tab==='안 읽음'&&!read.has(n.id)||n.category===tab);
 return `${button('돌아가기','home','','back')}${heading('알림함','확인할 소식을 모았어요.',button('모두 읽음','readAllAlerts'))}<div class="row">${button('알림 설정','notifications','','grow')}${button('보상함','rewards','','grow')}</div><nav class="tabs notice-tabs" aria-label="알림 분류">${['전체','안 읽음','시세','예약','보상','성장','뉴스','친구','공지','대화'].map(t=>button(t,'inboxTab',`data-tab="${t}" aria-pressed="${tab===t}"`,tab===t?'selected':'')).join('')}</nav>${filtered.map(n=>`<article class="card notice ${read.has(n.id)?'is-read':''}"><div class="row spread"><span class="tag">${n.category}</span><small>${read.has(n.id)?'읽음':'● 새 알림'}</small></div><h3>${e(n.title)}</h3><p>${e(n.body)}</p><small>${stamp(n.at)}</small><div class="row">${read.has(n.id)?'':button('읽음','readAlert',`data-id="${e(n.id)}"`,'grow')}${n.symbol?button('종목 보기','detail',`data-symbol="${e(n.symbol)}"`,'grow'):''}${n.kind==='attendance'?button('출석 보상','attendance','','grow'):n.category==='보상'?button('보상 확인','rewards','','grow'):n.category==='성장'?button('업적 확인','achievements','','grow'):n.category==='예약'?button('예약 확인','orders','','grow'):n.category==='뉴스'?button('뉴스 보기','news','','grow'):n.kind==='supportReply'?button('답변 확인','support','','grow'):n.category==='친구'||n.kind==='friendMessage'?button('친구 보기','friends','','grow'):''}</div></article>`).join('')||'<p class="empty">이 분류의 알림이 없습니다.</p>'}<section class="card"><h3>내 목표가</h3>${(s.priceAlerts||[]).map(n=>`<p>${e(s.stocks.find(x=>x.id===n.symbol)?.name)} · ${money(n.price)} ${n.direction==='above'?'이상':'이하'} · ${n.triggered?'도달':'대기'} ${button('삭제','removePriceAlert',`data-id="${n.id}"`,'link-button')}</p>`).join('')||'<p class="muted">종목 상세에서 목표가를 설정하세요.</p>'}</section>`;
}
export function receipt(r){return `<div class="tag gold">체결 완료</div><h3 style="margin:15px 0">${e(r.name)} · ${r.side==='buy'?'매수':'매도'}</h3><div class="receipt">${row('체결시각',stamp(r.at))}${row('수량 / 체결가',`${r.quantity}주 / ${money(r.price)}`)}${row('거래대금',money(r.gross))}${row('수수료 0.05%',money(r.fee))}${row(`세금 ${(r.taxRate*100).toFixed(2)}%`,money(r.tax))}${(r.taxDetails||[]).map(t=>row(e(t.name),money(t.amount))).join('')}${row('총비용',money(r.totalCost))}<div class="total"><span>${r.side==='buy'?'최종 출금':'최종 입금'}</span><strong>${money(r.net)}</strong></div>${row('거래 후 잔액',money(r.cashAfter))}${r.realized!==undefined?row('실현손익',money(r.realized)):''}</div><p class="footnote">체결번호 ${e(r.id)}<br>주문번호 ${e(r.orderId)}<br>과세 규칙 ${e(r.taxVersion)}</p>${r.memo?`<p class="card">투자 메모: ${e(r.memo)}</p>`:''}${r.currentPrice!==undefined?`<div class="card receipt">${row('현재 주가',money(r.currentPrice))}${r.currentHoldingProfit!==null?row('현재 보유분 전체 평가손익',money(r.currentHoldingProfit)):''}<p class="footnote">현재 상태 참고값이며 과거 영수증 금액과 별도입니다.</p></div>`:''}${r.newsAtTrade?.length?`<section class="section"><h3>거래 당시 관련 뉴스</h3>${r.newsAtTrade.map(n=>`<article class="news-card"><h3>${e(n.title)}</h3><p>${e(n.fact)}</p><small>${stamp(n.at)}</small></article>`).join('')}</section>`:''}`;}
export function achievements(s){
 const targets=s.achievementTargets||{assets:[12000000,15000000,20000000,50000000,100000000,500000000,1000000000,10000000000],realized:[1000000,5000000,10000000,20000000,100000000,500000000,1000000000],shares:[10,100,1000,10000,100000],companies:[3,5,10,15,20,30],news:[10,50,100,300,1000,3000],time:[1800,7200,18000,36000,90000,180000],holding:[3,7,30,90,180,365],dates:[3,7,30,90,180,365],industries:[3,5,6],explore:[5,15,30],memos:[1,5,10]},earned=s.account.achievements;
 const progressText=(kind,value)=>kind==='time'?(value<3600?Math.floor(value/60)+'분':Math.floor(value/3600)+'시간 '+Math.floor(value%3600/60)+'분'):value.toLocaleString('ko-KR');
 const stage=(kind,goal)=>{const a=earned[kind+'-'+goal],v=Math.max(0,s.account.statistics.progress?.[kind]||0);return `<li class="achievement-stage"><div class="row spread"><strong>${e(achievementName({kind,goal}))}</strong><span class="tag ${a?'gold':''}">${a?'달성':'진행 중'}</span></div>${a?'<small>'+stamp(a.at)+'</small>':'<p class="muted">'+progressText(kind,Math.min(v,goal))+' / '+progressText(kind,goal)+'</p>'}</li>`;};
 return `${button('돌아가기','home','','back')}${heading('나의 업적','배지를 모아 나의 기록을 완성해요.')}${Object.entries(targets).map(([kind,goals],index)=>{const done=goals.filter(goal=>earned[kind+'-'+goal]),next=goals.find(goal=>!earned[kind+'-'+goal]),goal=next||goals.at(-1),v=Math.max(0,s.account.statistics.progress?.[kind]||0);return '<details class="achievement-group tone-'+index%4+'" data-achievement="'+kind+'"><summary><span class="achievement-icon" aria-hidden="true">'+(next?'☆':'★')+'</span><span class="achievement-summary"><strong>'+e(kinds[kind])+'</strong><span>'+e(next?achievementName({kind,goal}):'모든 단계 달성')+'</span><small>'+done.length+' / '+goals.length+'개 달성 · 보상: 배지</small></span><span class="achievement-chevron" aria-hidden="true">▼</span></summary><div class="achievement-progress"><div class="bar"><span style="width:'+(next?Math.min(100,v/goal*100):100)+'%"></span></div></div><ol>'+goals.map(goal=>stage(kind,goal)).join('')+'</ol></details>';}).join('')}${Object.values(earned).filter(a=>a.kind==='reward').map(a=>'<div class="card"><span class="tag gold">특별 배지</span><h3>'+e(achievementName(a))+'</h3></div>').join('')}`;
}
export function settings(s){const a=s.account;return `${heading('설정','나에게 맞는 투자 환경')}<div class="card"><h3>${e(a.name)}님의 계정</h3><p class="muted">가입 ${stamp(a.joined).slice(0,10)}<br>최근 로그인 ${stamp(a.lastLogin).slice(0,10)}<br>누적 로그인 ${a.logins}회<br>총 플레이 시간 ${Math.floor(a.lifetimeSeconds/60)}분</p><div class="row" style="margin-top:15px">${button('수동 저장','save','','grow')}${button('비밀번호 변경','pin','','grow')}${button('로그아웃','logout','','grow')}</div></div><form id="settings-form" class="card"><h3>소리와 화면</h3><label>배경음악 음량<input name="bgm" type="range" min="0" max="1" step="0.05" value="${a.settings.bgm}"></label><label>효과음 음량<input name="sfx" type="range" min="0" max="1" step="0.05" value="${a.settings.sfx}"></label><label class="check"><input name="terms" type="checkbox" ${a.settings.terms?'checked':''}>용어 설명</label><p class="footnote">변경 즉시 이 브라우저에 저장됩니다. 음악은 화면을 조작한 뒤 재생되며 기기의 움직임 줄이기 설정을 적용합니다.</p></form><div class="list">${button('계정 로그 확인','records')}${button('업데이트 기록','updates')}${button('튜토리얼 다시 보기','tutorial')}${button('주식 용어 살펴보기','terms')}${button('앱 설치 안내','install')}${button('알림 수신 설정','notifications')}${button('백업 파일 내보내기','backup')}${button('백업 파일 불러오기','restore')}${button('고객센터','support')}${s.proxy?button('돌아가기','adminReturn'):s.admin?button('관리자 모드','admin'):''}${button('진행 상황 초기화','reset','','danger')}${button('회원 탈퇴','deleteAccount','','danger')}</div>`;}
