const CACHE='stock-king-v0.1.10-mobile-audit-20261008';
const ASSETS=['./','./index.html','./styles.css','./game-theme.css','./assets/ui/header.webp','./assets/favicon-transparent.png','./js/config.js','./js/api.js','./js/format.js','./js/game-panels.js','./js/views.js','./js/app.js','./js/admin-ui.js','./js/platform.js','./js/music.js','./js/friends-ui.js','./js/chat-ui.js','./js/optimistic.js','./js/preferences.js','./js/motion.js','./js/progression-ui.js','./js/news-content.js','./js/companies.js','./manifest.webmanifest','./assets/icon.svg','./assets/icon-192.png','./assets/icon-512.png','./assets/ui/reference/account.webp','./assets/ui/reference/backup.webp','./assets/ui/reference/bell.webp','./assets/ui/reference/book.webp','./assets/ui/reference/calendar.webp','./assets/ui/reference/cash.webp','./assets/ui/reference/coin.webp','./assets/ui/reference/graphics.webp','./assets/ui/reference/info.webp','./assets/ui/reference/loading-art.webp','./assets/ui/reference/masthead.webp','./assets/ui/reference/nav-assets.webp','./assets/ui/reference/nav-home.webp','./assets/ui/reference/nav-market.webp','./assets/ui/reference/nav-news.webp','./assets/ui/reference/nav-settings.webp','./assets/ui/reference/notification.webp','./assets/ui/reference/records.webp','./assets/ui/reference/reward-art.webp','./assets/ui/reference/reward-coin.webp','./assets/ui/reference/reward-gift.webp','./assets/ui/reference/reward-growth.webp','./assets/ui/reference/reward-mail.webp','./assets/ui/reference/sound.webp','./assets/ui/reference/support.webp','./assets/ui/reference/tile-assets.webp','./assets/ui/reference/tile-chest.webp','./assets/ui/reference/tile-gift.webp','./assets/ui/reference/tile-market.webp','./assets/ui/reference/tile-news.webp','./assets/ui/reference/tile-trophy.webp'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('stock-king-')&&k!==CACHE).map(k=>caches.delete(k))))));
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);if(event.request.method!=='GET'||url.origin!==self.location.origin)return;
 const scope=new URL(self.registration.scope);if(!ASSETS.some(path=>new URL(path,scope).pathname===url.pathname))return;
 event.respondWith(fetch(event.request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));}return response;}).catch(()=>caches.match(event.request).then(value=>value||Response.error())));
});
