const {test}=require('node:test'),assert=require('node:assert/strict');
const {harness,signup}=require('./helpers.cjs');
test('ETF ledger values securities, cash, receivables and liabilities',()=>{const h=harness();assert.equal(typeof h.K.fundNAV,'function');assert.equal(h.K.fundNAV({positions:{a:10,b:20},cash:100,receivable:50,liability:25,units:25},{a:{price:100},b:{price:200}}),205);});
test('creation and redemption preserve per-unit NAV',()=>{const h=harness();h.K.initFunds(h.s);const f=h.s.market.stocks.ETF_ALL.fund;const nav=h.K.fundNAV(f,h.s.market.stocks);h.K.fundUnits(f,1000,h.s.market.stocks);assert.ok(Math.abs(h.K.fundNAV(f,h.s.market.stocks)-nav)<1e-8);h.K.fundUnits(f,-1000,h.s.market.stocks);assert.ok(Math.abs(h.K.fundNAV(f,h.s.market.stocks)-nav)<1e-8);});
test('dividend claim moves receivable into cash without increasing assets twice',()=>{const h=harness(),a=signup(h),id=a.snapshot.account.id;h.s.claims.c={id:'c',accountId:id,runId:a.snapshot.account.runId,status:'대기',net:846,gross:1000,tax:154,payAt:h.now,symbol:'005930'};const before=h.call('sync',{token:a.token}).snapshot.total;const req={token:a.token,runId:a.snapshot.account.runId,requestId:'claim-0001',claimId:'c'};const after=h.call('claim',req);assert.equal(after.snapshot.account.cash,1000846);assert.equal(after.snapshot.total,before);assert.equal(h.call('claim',req).snapshot.total,before);});
test('reset clears lifetime progress and invalidates old rights, orders and backups',()=>{const h=harness(),a=signup(h),id=a.snapshot.account.id;const backup=h.call('backup',{token:a.token}).backup;h.s.accounts[id].lifetimeSeconds=900;h.s.claims.c={id:'c',accountId:id,runId:a.snapshot.account.runId,status:'대기',net:100,payAt:h.now};const r=h.call('reset',{token:a.token,runId:a.snapshot.account.runId,requestId:'reset-0001',pin:'0123',confirm:true});assert.equal(r.snapshot.day,1);assert.equal(r.snapshot.account.lifetimeSeconds,0);assert.equal(r.snapshot.account.joined,a.snapshot.account.joined);assert.equal(r.snapshot.dividends,0);assert.throws(()=>h.call('restore',{token:h.call('login',{name:'투자자',pin:'0123'}).token,runId:r.snapshot.account.runId,requestId:'restore-001',backup}),/백업/);});
test('ETF trading is locked server-side before DAY 4',()=>{const h=harness(),a=signup(h);h.K.initFunds(h.s);assert.throws(()=>h.call('quote',{token:a.token,symbol:'ETF_ALL',side:'buy',quantity:1}),/DAY 4/);});
test('PIN change invalidates every previous session',()=>{const h=harness(),a=signup(h);h.call('pin',{token:a.token,runId:a.snapshot.account.runId,requestId:'pin-00001',pin:'0123',newPin:'0012'});assert.throws(()=>h.call('sync',{token:a.token}),/인증/);const b=h.call('login',{name:'투자자',pin:'0012'});assert.equal(b.snapshot.account.cash,1000000);});
test('active intervals from two tabs are not counted twice',()=>{const h=harness(),a=signup(h);h.call('sync',{token:a.token,active:true});h.advance(60000);h.call('sync',{token:a.token,active:true});assert.equal(h.call('sync',{token:a.token,active:true}).snapshot.account.playSeconds,60);h.advance(3600000);assert.equal(h.call('sync',{token:a.token,active:true}).snapshot.account.playSeconds,60);});
