const {test}=require('node:test');
const assert=require('node:assert/strict');
const {harness,signup}=require('./helpers.cjs');
test('Korean midnight advances DAY without waiting 24 hours',()=>{const h=harness(),a=signup(h);assert.equal(a.snapshot.day,1);h.advance(60000);assert.equal(h.call('sync',{token:a.token}).snapshot.day,2);});
test('requires auth and only returns the current account',()=>{const h=harness();signup(h,'다른사람');const a=signup(h);assert.throws(()=>h.call('sync'),/인증/);assert.equal(a.snapshot.account.name,'투자자');assert.equal(JSON.stringify(a).includes('0123'),false);assert.equal(JSON.stringify(a).includes('다른사람'),false);assert.throws(()=>signup(h,'abc'),/한글/);assert.throws(()=>signup(h),/사용 중/);});
test('quote and execution charge exact fees once despite retry',()=>{const h=harness(),a=signup(h),q=h.call('quote',{token:a.token,symbol:'005930',side:'buy',quantity:10});const req={token:a.token,runId:a.snapshot.account.runId,requestId:'trade-0001',quoteId:q.quote.id};const r=h.call('trade',req),cash=r.snapshot.account.cash;assert.equal(r.receipt.gross,700000);assert.equal(r.receipt.fee,350);assert.equal(cash,299650);assert.equal(h.call('trade',req).snapshot.account.cash,cash);assert.equal(h.s.accounts[a.snapshot.account.id].holdings['005930'].quantity,10);});
test('stale quote and forged run cannot change holdings',()=>{const h=harness(),a=signup(h),q=h.call('quote',{token:a.token,symbol:'005930',side:'buy',quantity:1});h.advance(21000);assert.throws(()=>h.call('trade',{token:a.token,runId:a.snapshot.account.runId,requestId:'stale-0001',quoteId:q.quote.id}),/시세/);assert.throws(()=>h.call('order',{token:a.token,runId:'old',requestId:'old',symbol:'005930',kind:'limitBuy',quantity:1,price:70000}),/회차/);});
test('reserved cash prevents overspending; cancelling releases it',()=>{const h=harness(),a=signup(h);const r=h.call('order',{token:a.token,runId:a.snapshot.account.runId,requestId:'reserve-0001',symbol:'005930',kind:'limitBuy',quantity:10,price:60000,expiryDays:7});assert.equal(r.snapshot.availableCash,399700);assert.throws(()=>h.call('order',{token:a.token,runId:a.snapshot.account.runId,requestId:'excess-0001',symbol:'005930',kind:'limitBuy',quantity:10,price:60000,expiryDays:7}),/현금/);h.call('cancel',{token:a.token,runId:a.snapshot.account.runId,requestId:'cancel-0001',orderId:r.order.id});assert.equal(h.call('sync',{token:a.token}).snapshot.availableCash,1000000);});
test('missed intervals are identical to minute by minute processing',()=>{const h=harness();const start=h.K.initial(h.now),a=structuredClone(start),b=structuredClone(start);h.K.advance(a,h.now+600000,h.env);for(let n=1;n<=10;n++)h.K.advance(b,h.now+n*60000,h.env);assert.deepEqual(JSON.parse(JSON.stringify(a.market)),JSON.parse(JSON.stringify(b.market)));});
