const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
function engine(){const ctx=vm.createContext({console});for(const f of fs.readdirSync('server').filter(f=>f.endsWith('.gs')&&!['Code.gs','Storage.gs'].includes(f)))vm.runInContext(fs.readFileSync('server/'+f,'utf8'),ctx,{filename:f});return ctx.King;}
function harness(){const K=engine();let now=Date.parse('2026-09-26T14:59:00Z');let n=0;const env={now:()=>now,id:()=>`id-${++n}-abcdefghijk`,hash:s=>crypto.createHash('sha256').update(s).digest('hex'),sign:s=>crypto.createHmac('sha256','test-only').update(s).digest('hex'),isAdmin:name=>name==='운영자',adminCheck:s=>s==='test-only-admin'};let state=K.initial(now);function call(action,data={}){const out=K.execute(state,{action,version:1,...data},env);state=out.state;return out.response;}return {K,call,env,get s(){return state;},get now(){return now;},time:n=>now=n,advance:ms=>now+=ms};}
function signup(h,name='투자자'){return h.call('signup',{name,pin:'0123',consent:true,requestId:'signup-'+name,remember:true});}
test('Korean midnight advances DAY without waiting 24 hours',()=>{const h=harness(),a=signup(h);assert.equal(a.snapshot.day,1);h.advance(60000);assert.equal(h.call('sync',{token:a.token}).snapshot.day,2);});
test('requires auth and only returns the current account',()=>{const h=harness();signup(h,'다른사람');const a=signup(h);assert.throws(()=>h.call('sync'),/인증/);assert.equal(a.snapshot.account.name,'투자자');assert.equal(JSON.stringify(a).includes('0123'),false);assert.equal(JSON.stringify(a).includes('다른사람'),false);assert.throws(()=>signup(h,'abc'),/한글/);assert.throws(()=>signup(h),/사용 중/);});
test('quote and execution charge exact fees once despite retry',()=>{const h=harness(),a=signup(h),q=h.call('quote',{token:a.token,symbol:'005930',side:'buy',quantity:10});const req={token:a.token,runId:a.snapshot.account.runId,requestId:'trade-0001',quoteId:q.quote.id};const r=h.call('trade',req),cash=r.snapshot.account.cash;assert.equal(r.receipt.gross,700000);assert.equal(r.receipt.fee,350);assert.equal(cash,9299650);assert.equal(h.call('trade',req).snapshot.account.cash,cash);assert.equal(h.s.accounts[a.snapshot.account.id].holdings['005930'].quantity,10);});
test('stale quote and forged run cannot change holdings',()=>{const h=harness(),a=signup(h),q=h.call('quote',{token:a.token,symbol:'005930',side:'buy',quantity:1});h.advance(21000);assert.throws(()=>h.call('trade',{token:a.token,runId:a.snapshot.account.runId,requestId:'stale-0001',quoteId:q.quote.id}),/시세/);assert.throws(()=>h.call('order',{token:a.token,runId:'old',requestId:'old',symbol:'005930',kind:'limitBuy',quantity:1,price:70000}),/회차/);});
test('reserved cash prevents overspending; cancelling releases it',()=>{const h=harness(),a=signup(h);const r=h.call('order',{token:a.token,runId:a.snapshot.account.runId,requestId:'reserve-0001',symbol:'005930',kind:'limitBuy',quantity:100,price:60000,expiryDays:7});assert.equal(r.snapshot.availableCash,3997000);assert.throws(()=>h.call('order',{token:a.token,runId:a.snapshot.account.runId,requestId:'excess-0001',symbol:'005930',kind:'limitBuy',quantity:100,price:60000,expiryDays:7}),/현금/);h.call('cancel',{token:a.token,runId:a.snapshot.account.runId,requestId:'cancel-0001',orderId:r.order.id});assert.equal(h.call('sync',{token:a.token}).snapshot.availableCash,10000000);});
test('missed intervals are identical to minute by minute processing',()=>{const h=harness();const start=h.K.initial(h.now),a=structuredClone(start),b=structuredClone(start);h.K.advance(a,h.now+600000,h.env);for(let n=1;n<=10;n++)h.K.advance(b,h.now+n*60000,h.env);assert.deepEqual(JSON.parse(JSON.stringify(a.market)),JSON.parse(JSON.stringify(b.market)));});
module.exports={harness,signup};

