const {test}=require('node:test'),assert=require('node:assert/strict');const {harness,signup}=require('./helpers.cjs');
function auth(a,id){return {token:a.token,runId:a.snapshot.account.runId,requestId:id};}
test('OCO reserves once and one fill cancels its opposite condition',()=>{const h=harness(),a=signup(h),q=h.call('quote',{token:a.token,symbol:'005930',side:'buy',quantity:10});h.call('trade',{...auth(a,'buy-oco-001'),quoteId:q.quote.id});const o=h.call('order',{...auth(a,'oco-000001'),symbol:'005930',kind:'oco',quantity:10,price:65000,stop:60000,expiryDays:7});assert.equal(o.snapshot.holdings['005930'].available,0);h.advance(60000);const r=h.call('sync',{token:a.token});assert.equal(r.snapshot.orders[0].status,'체결');assert.equal(r.snapshot.orders[0].otherLeg,'취소');assert.equal(r.snapshot.holdings['005930'],undefined);assert.equal(Object.values(h.s.receipts).length,2);});
test('limit orders do not execute retroactively, and expired orders release cash',()=>{const h=harness(),a=signup(h);h.call('order',{...auth(a,'buy-limit-01'),symbol:'005930',kind:'limitBuy',quantity:1,price:71000,expiryDays:1});assert.equal(h.call('sync',{token:a.token}).snapshot.holdings['005930'],undefined);h.s.market.stocks['005930'].status='거래정지';h.advance(86400000);for(let i=0;i<4;i++)h.call('sync',{token:a.token});const s=h.call('sync',{token:a.token}).snapshot;assert.equal(s.orders[0].status,'만료');assert.equal(s.availableCash,10000000);});
test('a later PIN retry cannot expose another account receipt',()=>{const h=harness(),a=signup(h),b=signup(h,'다른사람'),q=h.call('quote',{token:a.token,symbol:'005930',side:'buy',quantity:1}),r=h.call('trade',{...auth(a,'buy-private-01'),quoteId:q.quote.id});assert.throws(()=>h.call('receipt',{token:b.token,id:r.receipt.id}),/영수증/);});
test('public snapshots exclude PIN, server randomness, order actor flags and admin logs',()=>{const h=harness(),a=signup(h);h.call('order',{...auth(a,'private-order'),symbol:'005930',kind:'limitBuy',quantity:1,price:1});const r=h.call('sync',{token:a.token});assert.equal('admin' in r.snapshot.orders[0],false);const json=JSON.stringify(r);assert.equal(json.includes(h.s.market.seed),false);for(const field of ['"pin"','"audits"','"sessions"','"adminSessions"','"proxies"'])assert.equal(json.includes(field),false);});
test('rebalance preserves assets and weights stay within cap',()=>{const h=harness();h.K.initFunds(h.s);const x=h.s.market.stocks.ETF_CHIP,before=h.K.fundNAV(x.fund,h.s.market.stocks);h.K.rebalance(h.s,x);assert.ok(Math.abs(h.K.fundNAV(x.fund,h.s.market.stocks)-before)<1e-8);const values=Object.entries(x.fund.positions).map(([id,q])=>q*h.s.market.stocks[id].price);assert.equal(values.length,4);assert.ok(Math.max(...values)/(x.fund.units*before)<=.35);});
test('dividend ex adjustment and fund receivable conserve pretax assets',()=>{const h=harness(),a=signup(h),q=h.call('quote',{token:a.token,symbol:'005930',side:'buy',quantity:10});h.call('trade',{...auth(a,'buy-dividend'),quoteId:q.quote.id});h.K.initFunds(h.s);const x=h.s.market.stocks['005930'],fund=h.s.market.stocks.ETF_ALL.fund,before=h.K.fundNAV(fund,h.s.market.stocks);h.K.makeDividend(h.s,x,100,h.now,h.now+3600000,h.env);assert.equal(x.price,69900);assert.equal(x.base,69900);assert.ok(Math.abs(h.K.fundNAV(fund,h.s.market.stocks)-before)<1e-8);const claim=Object.values(h.s.claims)[0];assert.equal(claim.gross,1000);assert.equal(claim.net,846);const r=h.call('claim',{...auth(a,'early-claim1'),claimId:'all'});assert.equal(r.claimed.length,0);});
test('long market catchup blocks trades until chronological processing completes',()=>{const h=harness(),a=signup(h);h.advance(86400000);const r=h.call('quote',{token:a.token,symbol:'005930',side:'buy',quantity:1});assert.equal(r.error,'MARKET_CATCHUP');assert.equal(Object.keys(h.s.receipts).length,0);});
