var King = typeof King === 'undefined' ? {} : King;
King.fundNAV = function(f,stocks) {return (Object.keys(f.positions).reduce(function(v,id){return v+f.positions[id]*(stocks[id].status==='비상장'?0:stocks[id].price);},0)+f.cash+f.receivable-f.liability)/f.units;};
King.weights = function(stocks) {var free=stocks.slice(),left=1,w={};while(free.length){var cap=free.reduce(function(v,x){return v+x.float*x.price;},0),large=free.filter(function(x){return left*x.float*x.price/cap>.35;});if(!large.length){free.forEach(function(x){w[x.id]=left*x.float*x.price/cap;});break;}large.forEach(function(x){w[x.id]=.35;left-=.35;});free=free.filter(function(x){return !w[x.id];});}return w;};
King.rebalance = function(s,x) {var f=x.fund,stocks=Object.values(s.market.stocks).filter(function(v){return v.market!=='ETF'&&v.status==='상장'&&(f.kind==='전체시장'||v.sector===f.kind);});if(stocks.length<4)return;var budget=Object.keys(f.positions).reduce(function(v,id){return v+f.positions[id]*(s.market.stocks[id].status==='비상장'?0:s.market.stocks[id].price);},0)+Math.max(0,f.cash-f.distributable),w=King.weights(stocks);f.cash-=Math.max(0,f.cash-f.distributable);f.positions={};stocks.forEach(function(v){var q=Math.floor(budget*w[v.id]/v.price);f.positions[v.id]=q;f.cash-=q*v.price;});f.cash+=budget;};
King.initFunds = function(s) {['전체시장','반도체','소비재'].forEach(function(kind,i){var id=['ETF_ALL','ETF_CHIP','ETF_CONSUMER'][i];if(s.market.stocks[id])return;var t=s.market.minute*60000,f={kind,positions:{},cash:1000000000,receivable:0,liability:0,units:100000,distributable:0,feeCarry:0,lastFee:t};var x={id,name:'KING '+kind,sector:kind,market:'ETF',status:'상장',price:10000,base:10000,high:10000,low:10000,listed:King.date(t),description:'가상 구성자산 장부를 바탕으로 운용하는 '+kind+' ETF. 연 보수 0.2%, 주간 재조정과 분배.',fund:f,history:[[t,10000]],nav:10000,iNAV:10000,premium:0};s.market.stocks[id]=x;King.rebalance(s,x);});};
King.fundUnits = function(f,delta,stocks) {if(!Number.isSafeInteger(delta)||f.units+delta<=0)King.fail('발행 좌수를 확인해 주세요.');var ratio=delta/f.units;Object.keys(f.positions).forEach(function(id){f.positions[id]*=1+ratio;});f.cash*=1+ratio;f.receivable*=1+ratio;f.liability*=1+ratio;f.distributable*=1+ratio;f.units+=delta;};
King.updateFunds = function(s,t) {King.initFunds(s);Object.values(s.market.stocks).filter(function(x){return x.fund;}).forEach(function(x){var f=x.fund,value=King.fundNAV(f,s.market.stocks)*f.units;f.feeCarry+=Math.max(0,value)*.002*(t-f.lastFee)/(365*King.DAY);var fee=Math.floor(f.feeCarry);f.feeCarry-=fee;f.cash-=fee;f.lastFee=t;x.iNAV=King.fundNAV(f,s.market.stocks);var target=(King.random(x.id+':'+s.market.minute)-.5)*.002;x.premium=Math.max(-.005,Math.min(.005,(x.premium||0)*.8+target*.2));x.price=Math.max(1,Math.round(x.iNAV*(1+x.premium)));if((t+32400000)%King.DAY===0)x.nav=x.iNAV;x.high=Math.max(x.high,x.price);x.low=Math.min(x.low,x.price);x.history.push([t,x.price]);});};
King.makeDividend = function(s,x,perShare,t,payAt,env) {
  if(!perShare)return;
  Object.values(s.accounts).forEach(function(a){var h=a.holdings[x.id];if(!h||!h.quantity)return;var gross=h.quantity*perShare,tax=Math.ceil(gross*.154),id=env.id();s.claims[id]={id,accountId:a.id,runId:a.runId,symbol:x.id,name:x.name,quantity:h.quantity,gross,tax,taxRate:.154,taxVersion:'game-tax-v1',net:gross-tax,at:t,payAt,status:'대기'};King.log(s,a,x.fund?'분배 권리 확정':'배당 권리 확정',s.claims[id],t,env);});
  x.price=Math.max(1,x.price-perShare);x.base=Math.max(1,x.base-perShare);if(x.fund){x.fund.liability+=perShare*x.fund.units;}else {x.fundamental=Math.max(1,x.fundamental-perShare);Object.values(s.market.stocks).filter(function(v){return v.fund;}).forEach(function(v){var amount=(v.fund.positions[x.id]||0)*perShare;v.fund.receivable+=amount;s.market.calendar.push({id:env.id(),type:'펀드배당',symbol:v.id,amount,payAt});});}
};
